targets:
  $default:
    builders:
      discord:slash_commands:
        enabled: true

builders:
  slash_commands:
    import: "package:discord/src/builders/slash_commands.dart"
    builder_factories:
      - commandBuilder
    build_extensions:
      .dart:
        - .discord.g.part
    auto_apply: root_package
    build_to: cache
    applies_builders:
      - source_gen:combining_builder