// This file is auto-generated by recursive_caster.
// It's recommended to add this file to your gitignore, as it can be regenerated using your configuration file.

// Any modifications to this file are not saved. If you need customizations that this package doesn't provide, feel free to make an issue or pull request on GitHub.
// You shouldn't try to read this file, as it'll be harder to follow than the actual generator script.



// -------------------- START GENERATION -------------------- //
/// This is the main class for the casting library.
class RecursiveCaster {
  RecursiveCaster._();
  /// This function is the bridge to the generated casting code and your code. [T] is the type you are requesting the conversion to. If [T] is not in the generated list, then a [RecursiveCasterTypeError] is thrown. Currently supported types are:
  ///
  /// - [Map<String, String>] (`Map<String, String>`)
  static T cast<T>(Object? input) {
    if (T == Map<String, String>) return ((dynamic value) => Map<String, String>.from(value.map((e, a) => MapEntry(e as String, a as String))))(input) as T;
    throw RecursiveCasterTypeError(T);
  }
  /// This function returns an [Iterable<Type>] of all types supported by your configuration.
  static Iterable<Type> getAll() => [Map<String, String>];
}
/// This error is called if a casting object is not defined for the specified type.
class RecursiveCasterTypeError extends Error {
  /// The type that was specified.
  final Type type;
  /// This error is called if a casting object is not defined for the specified type.
  ///
  /// [type] is the type that was specified.
  RecursiveCasterTypeError(this.type);
  @override
  String toString() => "RecursiveCasterTypeError: Could not find type $type to be casted. (Did you forget to add the type to your configuration?)";
}